// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlx3fHRjNFIUh24xb-BCIW3FycqXnHEk',
    appId: '1:700026515295:web:7d4f3d3c0dc6065ee390ea',
    messagingSenderId: '700026515295',
    projectId: 'gamificationtasktracker',
    authDomain: 'gamificationtasktracker.firebaseapp.com',
    storageBucket: 'gamificationtasktracker.firebasestorage.app',
    measurementId: 'G-1L8MFDVCCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGJWIjjmUXVu8qo99RWE0RLLwB1ife2c',
    appId: '1:700026515295:android:adf8d5ee47b40253e390ea',
    messagingSenderId: '700026515295',
    projectId: 'gamificationtasktracker',
    storageBucket: 'gamificationtasktracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXixqq2jl9wYscB8JZ-Y4sdLfPrJYQ6u8',
    appId: '1:700026515295:ios:9bba8c5308e3077be390ea',
    messagingSenderId: '700026515295',
    projectId: 'gamificationtasktracker',
    storageBucket: 'gamificationtasktracker.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXixqq2jl9wYscB8JZ-Y4sdLfPrJYQ6u8',
    appId: '1:700026515295:ios:9bba8c5308e3077be390ea',
    messagingSenderId: '700026515295',
    projectId: 'gamificationtasktracker',
    storageBucket: 'gamificationtasktracker.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtlx3fHRjNFIUh24xb-BCIW3FycqXnHEk',
    appId: '1:700026515295:web:aa22f8116f833c62e390ea',
    messagingSenderId: '700026515295',
    projectId: 'gamificationtasktracker',
    authDomain: 'gamificationtasktracker.firebaseapp.com',
    storageBucket: 'gamificationtasktracker.firebasestorage.app',
    measurementId: 'G-MV7BM9B157',
  );

}